import type { Metadata } from "next";
import Link from "next/link";
import { BarList } from "@/components/ui/bar-list";
import { Card, CardHeader, PageHeader, Stat } from "@/components/ui/primitives";
import { TimeChart } from "@/components/ui/time-chart";
import { CURRENT_BRAND_ID } from "@/lib/data/brands";
import { analyticsFor, weekly } from "@/lib/queries";
import { cn, formatMoney, formatNumber } from "@/lib/utils";

export const metadata: Metadata = { title: "Analytics" };
export const dynamic = "force-dynamic";

const RANGES = [
  [30, "Last 30 days"],
  [90, "Last 90 days"],
  [120, "Last 120 days"],
] as const;

export default async function AnalyticsPage({ searchParams }: PageProps<"/analytics">) {
  const sp = await searchParams;
  const days = RANGES.find(([d]) => String(d) === sp.range)?.[0] ?? 90;
  const a = analyticsFor(CURRENT_BRAND_ID, days);
  const money = (n: number) => formatMoney(n, "USD", { compact: n >= 10_000_000 });
  const rows = (list: { name: string; revenueCents: number; conversions: number }[]) =>
    list.slice(0, 6).map((r) => ({ label: r.name, value: r.revenueCents, sub: `${formatNumber(r.conversions)} conversions` }));

  return (
    <>
      <PageHeader title="Analytics" description="Performance across every partnership: revenue partners generate for you, and revenue you generate for them." />

      {/* Filters sit in one row above everything they scope. */}
      <div className="mb-6 flex flex-wrap gap-1.5" role="group" aria-label="Date range">
        {RANGES.map(([d, label]) => (
          <Link key={d} href={`/analytics?range=${d}`} aria-current={d === days ? "true" : undefined} className={cn("rounded-full border px-3.5 py-1.5 text-[13px] font-medium", d === days ? "border-ink bg-ink text-white" : "border-slate-200 bg-white text-slate-600 hover:border-slate-300")}>
            {label}
          </Link>
        ))}
      </div>

      <section aria-label="Key metrics" className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-4">
        <Stat label="Partner Revenue" value={money(a.partnerRevenueCents)} hint="Generated for you" />
        <Stat label="Revenue generated for partners" value={money(a.revenueForPartnersCents)} hint="Generated by you" />
        <Stat label="Clicks" value={formatNumber(a.clicks, true)} hint="All time, your links" />
        <Stat label="Conversions" value={formatNumber(a.conversions)} hint={`${(a.conversionRate * 100).toFixed(2)}% conversion rate`} />
        <Stat label="Average order value" value={formatMoney(a.aovCents)} />
        <Stat label="New customers" value={formatNumber(a.newCustomers)} hint={`${a.conversions ? Math.round((a.newCustomers / a.conversions) * 100) : 0}% of conversions`} />
        <Stat label="Commission owed" value={money(a.commissionOwedCents)} hint="Unpaid to partners" />
        <Stat label="Commission earned" value={money(a.commissionEarnedCents)} hint="From partners" />
        <Stat label="Flat fees paid" value={money(a.flatFeesCents)} />
        <Stat label="Total partnership cost" value={money(a.totalCostCents)} hint="Commission + flat fees" />
        <Stat label="ROAS" value={a.roas ? `${a.roas.toFixed(1)}×` : "—"} hint="Partner Revenue ÷ cost" />
        <Stat label="Active partnerships" value={a.activePartnerships} />
      </section>

      <Card className="mt-6">
        <CardHeader title="Revenue over time" description="Weekly sales attributed through partnerships" />
        <div className="p-5">
          <TimeChart
            points={weekly(a.series)}
            series={[
              { key: "partnerRevenue", label: "Partner Revenue", color: "var(--color-strand-indigo)" },
              { key: "revenueForPartners", label: "Revenue for partners", color: "var(--color-strand-teal)" },
            ]}
            unit="money"
            ariaLabel={`Weekly partner revenue and revenue for partners, last ${days} days`}
          />
        </div>
      </Card>

      <div className="mt-6 grid gap-6 md:grid-cols-2">
        <Card>
          <CardHeader title="Revenue by partner" />
          <div className="p-5">
            <BarList rows={rows(a.byPartner)} format={money} />
          </div>
        </Card>
        <Card>
          <CardHeader title="Revenue by campaign" />
          <div className="p-5">
            <BarList rows={rows(a.byCampaign)} format={money} />
          </div>
        </Card>
        <Card>
          <CardHeader title="Revenue by channel" />
          <div className="p-5">
            <BarList rows={rows(a.byChannel)} format={money} />
          </div>
        </Card>
        <Card>
          <CardHeader title="Revenue by geography" />
          <div className="p-5">
            <BarList rows={rows(a.byCountry)} format={money} />
          </div>
        </Card>
      </div>
      <p className="mt-4 text-xs text-slate-500">Reversed transactions are excluded. Product-level breakdowns arrive with line-item reporting in the conversion API.</p>
    </>
  );
}
